n=input("Enter your name")
a=int(input("Enter age"))
h=int(input("Enter height in cm"))
fp=input("Enter Favourite programming language")
fs=input("Enter Favourite sport")
print("=================================\nStudent Profile\n=================================")
print("Name: ",n)
print("Age: ",a)
print("Height: ",h,"cm")
print("Favourite programming language: ",fp)
print("Favourite sport: ",fs)
print("Welcome to Engineering!")